const A='assets/images/';
// Фактические данные меняются здесь — дизайн карточек и страниц останется прежним.
const settings={
  instagram:'https://www.instagram.com/la.natasha_',
  telegram:'https://t.me/rudenkonatashenka',
  whatsapp:'https://wa.me/351914417117',
  email:'mailto:rudenko.natasenka@gmail.com',
  youtube:'', // Канал можно добавить позже — пустое значение скрывает его на сайте.
  retreat:{title:'Название ретрита',place:'Место проведения',date:'Даты уточняются',price:'Стоимость уточняется',spots:'Количество мест',desc:'Добавьте описание ретрита.'}
};
const retreat=settings.retreat;
const placeholders={
  ocean:`<div class="placeholder"><div><b>Фотография океана / природы</b>Горизонтальный кадр 3:2, мягкий свет, без людей</div></div>`,
  video:`<div class="video-placeholder"><div><span class="play">▶</span><b>Видео будет добавлено позже</b><br><small>Атмосферный ролик 16:9, 30–60 секунд</small></div></div>`
};
const button=(text='Записаться')=>`<a class="button dark" href="${settings.whatsapp}" target="_blank" rel="noopener">${text}<span>↗</span></a>`;
const pageHero=(title,subtitle,img='',className='')=>`<section class="page-hero ${img?'has-image':''} ${className}">${img?`<div class="page-hero-bg"><img src="${A+img}" alt=""></div>`:''}<span class="breadcrumb">Главная&nbsp; / &nbsp;${title.replace(/<[^>]*>/g,'')}</span><div class="page-hero-content"><span class="eyebrow">Наташа · кундалини-йога</span><h1>${title}</h1><p>${subtitle}</p></div></section>`;
const home=()=>`
<section class="hero">
  <div class="hero-media"><img src="${A}hero-sunset.jpg" alt="Закат у океана в Португалии"></div>
  <div class="hero-content reveal"><span class="eyebrow light">Наташа · преподаватель кундалини-йоги</span><h1>Красивые люди<br><em>начинаются изнутри.</em></h1><p>Внутреннее состояние, которое меняет жизнь через инструменты кундалини-йоги.</p><div class="hero-actions">${button('Записаться')}<a class="button ghost" href="#/programs">Выбрать программу <span>→</span></a></div><div class="hero-proof"><div><small>Кто</small><b>Наташа</b></div><div><small>Чем помогает</small><b>Менять состояние</b></div><div><small>Инструмент</small><b>Кундалини-йога</b></div></div></div>
  <span class="scroll-note">Личный путь · личная работа</span>
</section>
<section class="portrait-manifesto"><div class="manifesto-photo"><img src="${A}portrait-city.jpg" alt="Наташа"></div><div class="manifesto-copy reveal"><span class="eyebrow light">Обо мне</span><p>Я не учу жить.</p><p>Я создаю пространство, в котором человек начинает слышать себя.</p><p>За годы работы я поняла:</p><p>красивые люди начинаются не с внешности.</p><p>Они начинаются с внутреннего состояния.</p><p>Поэтому главным инструментом стала кундалини-йога.</p><p>Практика, которая помогает успокоить ум, восстановить контакт с собой и начать менять жизнь изнутри.</p><p>Я не обещаю быстрых чудес.</p><p>Я помогаю человеку стать тем, кем он всегда хотел быть.</p><a class="text-link" href="#/about">Моя история <span>→</span></a></div></section>
<section class="section"><span class="eyebrow">Почему люди приходят ко мне</span><h2 class="section-title">Изменения, которые<br><em>начинаются внутри</em></h2><div class="benefits"><div class="benefit">спокойный ум</div><div class="benefit">больше энергии</div><div class="benefit">крепче нервная система</div><div class="benefit">ясность в жизни</div><div class="benefit">глубокий контакт с собой</div><div class="benefit">внутренняя опора</div></div></section>
${pricingSection()}
<section class="split-feature soft"><div class="split-image"><img src="${A}group-practice.jpg" alt="Практика с Наташей"></div><div class="split-copy reveal"><span class="num">РЕТРИТЫ С НАТАШЕЙ</span><span class="eyebrow">Личное сопровождение</span><h2>Практика, природа<br>и <em>глубокая работа</em></h2><p>${retreat.desc}</p><a class="text-link" href="#/retreats">Смотреть ретриты <span>→</span></a></div></section>`;
function programCard(title,text,img,meta){return `<article class="card reveal"><div class="card-media"><img src="${A+img}" alt="${title}" loading="lazy"><span class="badge">${meta}</span></div><div class="card-body"><span class="card-meta">Практика</span><h3>${title}</h3><p>${text}</p><a class="text-link" href="#/programs">Подробнее <span>→</span></a></div></article>`}
function priceCard(title,price,features,img){return `<article class="card pricing-card reveal"><div class="card-media"><img src="${A+img}" alt="${title}" loading="lazy"><span class="badge">С Наташей</span></div><div class="card-body"><span class="card-meta">Программа</span><h3>${title}</h3><div class="pricing">${price}</div><ul class="feature-list">${features.map(x=>`<li>${x}</li>`).join('')}</ul><a class="text-link" href="${settings.whatsapp}" target="_blank" rel="noopener">Записаться <span>→</span></a></div></article>`}
function pricingSection(){return `<section class="section soft"><span class="eyebrow">Практики с Наташей</span><h2 class="section-title">Выберите свой<br><em>формат работы</em></h2><div class="cards">${priceCard('ONLINE','290 € / месяц',['3 практики в неделю','Записи занятий','Закрытый чат','Поддержка'],'online-practice.jpg')}${priceCard('OFFLINE','490 € / месяц',['Живые практики','Небольшие группы','Глубокая работа','Поддержка'],'morning-practice.jpg')}${priceCard('Индивидуальная работа','от 890 € / месяц',['Персональная программа','Работа под запрос','Ежедневная поддержка'],'portrait-city.jpg')}</div></section>`}
const programs=()=>`${pageHero('Практики с Наташей','Внутреннее состояние, которое меняет жизнь через инструменты кундалини-йоги.','morning-practice.jpg')}${pricingSection()}
<section class="section"><div class="retreat-info"><div><span class="eyebrow">Работа со мной</span><h2 class="section-title">Глубокая работа<br><em>под запрос</em></h2></div><div><p class="lead">Я создаю пространство, в котором человек начинает слышать себя.</p>${button('Записаться')}</div></div></section>`;
function acc(title,body){return `<div class="acc-item"><button class="acc-head">${title}<span>＋</span></button><div class="acc-content">${body}</div></div>`}
const retreats=()=>`${pageHero('Ретриты с Наташей','Выходные с Наташей — это возможность на один или несколько дней выйти из привычного ритма жизни и посвятить время себе.<br><br>Практики кундалини-йоги, дыхательные техники, медитации, природа, тишина и живое общение помогают замедлиться, восстановить внутренний ресурс и почувствовать настоящее состояние своего тела и ума.<br><br>Каждая программа имеет свою тему, формат и продолжительность, но их объединяет одна цель — помочь вам перезагрузиться, наполниться энергией и вернуться к своей жизни с новым состоянием.','retreat-garden.jpg')}
<section class="section"><div class="retreat-info"><div><span class="eyebrow">Ближайший ретрит</span><h2 class="section-title">${retreat.title}<br><em>${retreat.place}</em></h2><p>${retreat.desc}</p><div class="facts"><div class="fact"><small>Даты</small><b>${retreat.date}</b></div><div class="fact"><small>Стоимость</small><b>${retreat.price}</b></div><div class="fact"><small>Группа</small><b>${retreat.spots}</b></div><div class="fact"><small>Место</small><b>${retreat.place}</b></div></div></div><div><img src="${A}sound-practice.jpg" alt="Звуковая практика на ретрите"></div></div></section>
<section class="section soft"><span class="eyebrow">Программа по дням</span><h2 class="section-title">Программа<br><em>будет добавлена</em></h2><div class="data-note">Добавьте фактическую программу ретрита по дням в блок настроек. Никакие даты или активности не придуманы.</div></section>
<section class="section"><div class="retreat-info"><div><span class="eyebrow">Условия</span><h2 class="section-title">Что входит<br>и что <em>взять</em></h2></div><div><div class="data-note">Добавьте подтверждённый список включённых услуг и вещей, которые участникам нужно взять с собой.</div>${button('Забронировать место')}</div></div><div class="gallery-grid"><figure><img src="${A}group-practice.jpg" alt="Групповая практика" loading="lazy"></figure><figure><img src="${A}retreat-details.jpg" alt="Детали ретрита" loading="lazy"></figure><figure><img src="${A}retreat-table.jpg" alt="Общий стол" loading="lazy"></figure><figure><img src="${A}horse-sunset.jpg" alt="Закат в Португалии" loading="lazy"></figure></div></section>`;
function review(text,name){return `<article class="review"><blockquote>«${text}»</blockquote><footer><span class="avatar">${name[0]}</span><span>${name}</span></footer></article>`}
const events=()=>`${pageHero('Ближайшие<br><em>встречи</em>','Ближайшие программы и живые встречи с Наташей.')}
<section class="section meetings-section"><div class="meetings-list">
  ${offlineMeeting('8','августа 2026','Практика на закате у океана','18:00','Costa da Caparica','Приглашаю вас провести красивый летний вечер на берегу океана.<br><br>Мы начнем с дыхательной практики, затем выполним крийю кундалини-йоги, после чего погрузимся в глубокую медитацию, чтобы отпустить напряжение, успокоить ум и наполниться энергией.<br><br>В завершение вместе встретим закат на берегу океана.<br><br>Практика подходит как для начинающих, так и для тех, кто уже знаком с кундалини-йогой.','15 €')}
  ${meeting('8','августа 2026','Деньги есть','7 дней','Каждый день мы будем работать с ограничивающими убеждениями, нервной системой, внутренним состоянием и отношением к деньгам через кундалини-йогу, дыхательные практики, медитации и осознанность.','Онлайн','111 €')}
  ${meeting('15','августа 2026','Начало','40 дней','Программа для тех, кто начинает знакомство с кундалини-йогой.<br><br>В течение 40 дней мы шаг за шагом будем работать с телом, дыханием, нервной системой и формировать привычку к регулярной практике.<br><br>Это первый этап большого пути к устойчивому внутреннему состоянию, здоровому телу и осознанной жизни.','Онлайн')}
</div></section>`;
function eventPrice(price){return price?`<div class="event-price"><span>Стоимость участия:</span><b>${price}</b></div>`:''}
function offlineMeeting(day,date,title,time,place,description,price){return `<article class="meeting meeting-offline reveal"><div class="meeting-date"><small>Дата</small><b>${day}</b><span>${date}</span></div><div class="meeting-content"><span class="card-meta">Ближайшая офлайн-встреча</span><h2>${title}</h2><div class="meeting-facts meeting-facts-three"><div><small>Время</small><b>${time}</b></div><div><small>Место</small><b>${place}</b></div><div><small>Формат</small><b>Оффлайн</b></div></div><p>${description}</p>${eventPrice(price)}<a class="text-link" href="${settings.whatsapp}" target="_blank" rel="noopener">Записаться <span>→</span></a></div></article>`}
function meeting(day,date,title,duration,description,type,price=''){return `<article class="meeting reveal"><div class="meeting-date"><small>Старт</small><b>${day}</b><span>${date}</span></div><div class="meeting-content"><span class="card-meta">Ближайшая программа</span><h2>${title}</h2><div class="meeting-facts"><div><small>Формат</small><b>${type}</b></div><div><small>Продолжительность</small><b>${duration}</b></div></div><p>${description}</p>${eventPrice(price)}<a class="text-link" href="${settings.whatsapp}" target="_blank" rel="noopener">Записаться <span>→</span></a></div></article>`}
function event(day,month,title,place,type){return `<article class="event" data-type="${type}"><div class="event-date"><b>${day}</b> <span>${month}</span></div><div><h3>${title}</h3><small>${place}</small></div><span class="event-type">${type}</span><button class="text-link" data-modal>Записаться <span>→</span></button></article>`}
const about=()=>`${pageHero('Наташа','Красивые люди начинаются изнутри.','portrait-city.jpg')}
<section class="intro-video" aria-label="Приветственное видео Наташи"><video controls playsinline preload="metadata" poster="${A}hero-sunset.jpg"><source src="assets/video/natasha-intro-web.mp4" type="video/mp4">Ваш браузер не поддерживает встроенное видео.</video></section>
<section class="portrait-manifesto"><div class="manifesto-photo"><img src="${A}about-natasha.jpg" alt="Наташа"></div><div class="manifesto-copy"><span class="eyebrow light">Обо мне</span><p>Я не учу жить.</p><p>Я создаю пространство, в котором человек начинает слышать себя.</p><p>За годы работы я поняла:</p><p>красивые люди начинаются не с внешности.</p><p>Они начинаются с внутреннего состояния.</p><p>Поэтому главным инструментом стала кундалини-йога.</p><p>Практика, которая помогает успокоить ум, восстановить контакт с собой и начать менять жизнь изнутри.</p><p>Я не обещаю быстрых чудес.</p><p>Я помогаю человеку стать тем, кем он всегда хотел быть.</p></div></section>`;
const reviews=()=>`${pageHero('Отзывы','Реальные истории людей, которые работали с Наташей.')}
<section class="section"><div class="testimonials"><article class="review"><blockquote>Здесь будет первый реальный отзыв.</blockquote><footer><span>Добавьте имя, фотографию и текст клиента</span></footer></article><article class="review"><blockquote>Здесь будет второй реальный отзыв.</blockquote><footer><span>Добавьте имя, фотографию и текст клиента</span></footer></article><article class="review">${placeholders.video}</article></div><div class="data-note">Вымышленные отзывы удалены. Новые отзывы добавляются одной строкой через функцию review() в app.js.</div></section>`;
const blog=()=>`${pageHero('Бесплатные<br><em>практики</em>','Начните знакомство с кундалини-йогой с двух коротких бесплатных практик. Каждая занимает всего 3 минуты и помогает быстро изменить внутреннее состояние.','free-practices-hero.jpg','free-library-hero')}
<section class="section practice-library"><div class="practice-library-grid">
  ${libraryCard('Пранаяма для снижения стресса','Короткая дыхательная практика продолжительностью 3 минуты, которая помогает успокоить нервную систему, снять внутреннее напряжение и вернуть ясность ума.','practice-pranayama-cover.jpg','#/practice/pranayama','Пранаяма')}
  ${libraryCard('Медитация «Перезагрузка»','Трёхминутная медитация кундалини-йоги для быстрого переключения внимания, восстановления концентрации и внутреннего спокойствия.','practice-meditation-cover.jpg','#/practice/meditation','Медитация')}
</div></section>`;
function libraryCard(title,description,img,href,type){return `<article class="library-card reveal"><a class="library-card-media" href="${href}" aria-label="${title}"><img src="${A+img}" alt="${title}" loading="lazy"><span>${type} · бесплатно</span></a><div class="library-card-copy"><h2>${title}</h2><p>${description}</p><a class="button dark" href="${href}">Смотреть бесплатно <span>→</span></a></div></article>`}
function practicePage(title,description,src,type){return `${pageHero(title,description)}<section class="section practice-detail"><a class="text-link practice-back" href="#/blog">← Все бесплатные практики</a><div class="practice-detail-grid"><div class="practice-detail-copy"><span class="eyebrow">${type} · бесплатно</span><h2 class="section-title">${title}</h2><p class="lead">${description}</p></div><div class="practice-detail-video"><video controls playsinline preload="metadata"><source src="${src}" type="video/mp4">Ваш браузер не поддерживает встроенное видео.</video></div></div></section>`}
const pranayamaPage=()=>practicePage('Пранаяма для снижения стресса','Короткая дыхательная практика продолжительностью 3 минуты, которая помогает успокоить нервную систему, снять внутреннее напряжение и вернуть ясность ума.','assets/video/pranayama-stress-web.mp4','Пранаяма');
const meditationPage=()=>practicePage('Медитация «Перезагрузка»','Трёхминутная медитация кундалини-йоги для быстрого переключения внимания, восстановления концентрации и внутреннего спокойствия.','assets/video/meditation-reset-web.mp4','Медитация');
const faq=()=>`${pageHero('Вопросы<br><em>и ответы</em>','Всё, что важно знать перед первой практикой.')}<section class="section"><div class="retreat-info"><div><span class="eyebrow">FAQ</span><h2 class="section-title">Можно начать<br><em>с любого места</em></h2></div><div class="accordion">${acc('Нужен ли опыт в йоге?','Нет. Я всегда даю варианты и помогаю выбрать интенсивность, которая подходит вашему состоянию.')}${acc('Подходит ли практика при ограничениях по здоровью?','Перед началом сообщите о диагнозах, беременности, травмах и принимаемых препаратах. Практика не заменяет медицинскую помощь.')}${acc('Что нужно для онлайн-занятия?','Тихое место, коврик или плед, вода и стабильная связь. Камеру можно включать по желанию.')}${acc('Можно ли отменить встречу?','Да, бесплатный перенос возможен не позднее чем за 24 часа до начала.')}${acc('Как забронировать ретрит?','Оставьте заявку. После короткого знакомства и подтверждения места вносится депозит.')}</div></div></section>`;
const icons={instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>',telegram:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 4 3 11l7 2.5L17 8l-5.5 7v5l3-3 4 3z"/></svg>',whatsapp:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.7A8 8 0 0 1 8.2 18.8L4 20l1.2-4.1A8 8 0 1 1 20 11.7z"/><path d="M9 8.5c.7 2 2 3.3 4 4l1-1c.2-.2.5-.2.7-.1l2 1c.3.1.4.4.3.7-.4 1.4-1.5 2-2.8 2-3.7-.4-6.8-3.5-7.2-7.2 0-1.3.6-2.4 2-2.8.3-.1.6 0 .7.3l1 2c.1.2.1.5-.1.7z"/></svg>',email:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>'};
function socialLink(label,url,icon){return url?`<a href="${url}" target="_blank" rel="noopener"><span class="social-name"><i>${icons[icon]}</i>${label}</span><span>↗</span></a>`:''}
const contacts=()=>`${pageHero('Связаться<br><em>с Наташей</em>','Запишитесь на практику или задайте вопрос лично Наташе.')}
<section class="section"><div class="contact-grid"><div><span class="eyebrow">Личный контакт</span><h2 class="section-title">Выберите удобный<br><em>способ связи</em></h2><div class="contact-links">${socialLink('Instagram',settings.instagram,'instagram')}${socialLink('Telegram',settings.telegram,'telegram')}${socialLink('WhatsApp',settings.whatsapp,'whatsapp')}${socialLink('rudenko.natasenka@gmail.com',settings.email,'email')}${socialLink('YouTube',settings.youtube,'youtube')}</div></div><form class="form" id="contactForm"><label>Ваше имя<input name="name" required placeholder="Как к вам обращаться"></label><label>Email<input name="email" type="email" required placeholder="mail@example.com"></label><label>Какой формат интересует?<input name="format" placeholder="Online, Offline или индивидуальная работа"></label><label>Ваше сообщение<textarea name="message" rows="5" placeholder="Расскажите немного о своём запросе"></textarea></label><button class="button dark" type="submit">Написать Наташе <span>↗</span></button></form></div></section>`;
const routes={'/':home,'/programs':programs,'/retreats':retreats,'/events':events,'/free':blog,'/about':about,'/reviews':reviews,'/blog':blog,'/practice/pranayama':pranayamaPage,'/practice/meditation':meditationPage,'/faq':faq,'/contacts':contacts};
function render(){const path=location.hash.slice(1)||'/';const view=routes[path]||routes['/'];document.getElementById('app').innerHTML=view();document.body.classList.toggle('home',path==='/');document.getElementById('header').classList.toggle('inner',path!=='/');document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${path}`));document.getElementById('nav').classList.remove('open');window.scrollTo(0,0);bind();requestAnimationFrame(observe)}
function bind(){document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>window.open(settings.whatsapp,'_blank','noopener'));document.querySelectorAll('.acc-head').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{c.parentElement.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active')});document.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);const msg=[`Здравствуйте, Наташа! Меня зовут ${d.get('name')||''}.`,d.get('format')?`Интересует: ${d.get('format')}.`:'',d.get('message')||''].filter(Boolean).join('\n');window.open(`${settings.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener')})}
function openModal(){const m=document.getElementById('modal');m.classList.add('open');m.setAttribute('aria-hidden','false')}
function toast(text){const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),4000)}
function observe(){const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>o.observe(el))}
window.addEventListener('hashchange',render);window.addEventListener('scroll',()=>document.getElementById('header').classList.toggle('scrolled',scrollY>30));
document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.querySelector('[data-close]').onclick=()=>document.getElementById('modal').classList.remove('open');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};render();
